name: Testinnnn sauce demo
on: push
jobs:
  xyinya:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo code
      uses: actions/checkout@v4

    - name: install browsers
      run: sudo apt-get update
          sudo apt-get install -y \
          libgtk-4-1 \
          libgraphene-1.0-0 \
          libwoff2dec0 \
          libvpx9 \
          libevent-2.1-7 \
          libopus0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          gstreamer1.0-gl \
          libflite1 \
          libavif16 \
          libharfbuzz-icu0 \
          libsecret-1-0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libgles2-mesa \
          libx264-160

    - name: install requirements
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: install pw browsers
      run: python -m playwright install

    - name: run test
      run: pytest

