name: Testinnnn sauce demo
on: push
jobs:
  xyinya:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo code
      uses: actions/checkout@v4
    - name: install requirements
      uses: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run test
      uses: pytest

